name: Java Test Runner

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create bin and libs folders
        run: |
          mkdir -p bin
          mkdir -p libs

      - name: Download JUnit 5 Console Standalone
        run: |
          curl -L -o libs/junit-platform-console-standalone.jar https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.10.1/junit-platform-console-standalone-1.10.1.jar

      - name: Compile Java source and test files
        run: |
          javac -d bin -cp libs/junit-platform-console-standalone.jar $(find Lab6/test Lab6/src Lab7/test Lab7/src -name "*.java")


      - name: Run JUnit tests
        run: |
          java -jar libs/junit-platform-console-standalone.jar \
            --classpath bin \
            --scan-class-path
