name: Java Build Check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create folders
        run: |
          mkdir -p bin
          mkdir -p libs

      - name: Download JUnit 5 Console Standalone
        run: |
          curl -L -o libs/junit-platform-console-standalone.jar \
          https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.10.2/junit-platform-console-standalone-1.10.2.jar

      - name: Compile Java files with JUnit
        run: |
          javac -d bin -cp libs/junit-platform-console-standalone.jar $(find src -name "*.java")

      - name: Run JUnit tests
        run: |
          java -jar libs/junit-platform-console-standalone.jar \
          --class-path bin \
          --scan-class-path
